version: 2
registries:
  maven-repository-maven-pkg-github-com-navikt-fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles/
    username: x-access-token
    password: "${{secrets.MAVEN_REPOSITORY_MAVEN_PKG_GITHUB_COM_NAVIKT_FP_FELLES_PASSWORD}}"

updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.google.cloud:google-cloud-bom
    versions:
    - 0.148.0
    - 0.149.0
    - 0.150.0
    - 0.151.0
    - 0.152.0
  - dependency-name: no.nav.familie.felles:http-client
    versions:
    - 1.20210223111349_05be6ea
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.familie.felles:log
    versions:
    - 1.20210223111349_05be6ea
    - 1.20210416135502_5bf9eff
  - dependency-name: no.nav.familie.kontrakter:felles
    versions:
    - 2.0_20210305131536_dd4cd5d
    - 2.0_20210312160913_1f140c8
    - 2.0_20210317125829_2bee9c0
  - dependency-name: org.springframework.boot:spring-boot-starter-parent
    versions:
    - 2.4.3
    - 2.4.4
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-plugin
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-maven-allopen
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-test-junit5
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-reflect
    versions:
    - 1.4.31
  - dependency-name: org.jetbrains.kotlin:kotlin-stdlib
    versions:
    - 1.4.31
  - dependency-name: org.testcontainers:junit-jupiter
    versions:
    - 1.15.2
  - dependency-name: org.verapdf:validation-model
    versions:
    - 1.18.2
  - dependency-name: org.testcontainers:localstack
    versions:
    - 1.15.2
  - dependency-name: no.nav.security:token-validation-test-support
    versions:
    - 1.3.3
  - dependency-name: no.nav.security:token-validation-spring
    versions:
    - 1.3.3
  - dependency-name: com.openhtmltopdf:openhtmltopdf-svg-support
    versions:
    - 1.0.6
  - dependency-name: com.openhtmltopdf:openhtmltopdf-pdfbox
    versions:
    - 1.0.6
  - dependency-name: com.openhtmltopdf:openhtmltopdf-core
    versions:
    - 1.0.6
  registries:
  - maven-repository-maven-pkg-github-com-navikt-fp-felles
