apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-dokument
  namespace: default
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  port: 8082
  liveness:
    path: /familie/alene-med-barn/mellomlagring/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /familie/alene-med-barn/mellomlagring/internal/status/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/mellomlagring/internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 2048Mi
      cpu: "1"
    requests:
      memory: 1024Mi
      cpu: 500m
  secureLogs:
    enabled: true
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-dokument.nais.oera.no
    - https://www.nav.no/familie/alene-med-barn/mellomlagring
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - configmap: loginservice-idporten