no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: http://localhost:8080/metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken

FAMILIE_DOKUMENT_STORAGE_ENCRYPTION_PASSWORD: not-a-real-pw
SOKNAD_PDF_SVG_SUPPORT_GENERATOR_URL: #mockes ut lokalt
FAMILIE_DOKUMENT_S3_ACCESSKEY: not-a-real-key
FAMILIE_DOKUMENT_S3_SECRETKEY: not-a-real-key