server:
  port: 8082
  servlet:
    context-path: /
cors:
  allowed_origins:
    - "http://localhost:3000"

no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: http://metadata
    accepted_audience: aud-localhost
    cookie_name: localhost-idtoken
    proxyurl:

FAMILIE_DOKUMENT_STORAGE_ENCRYPTION_PASSWORD: not-a-real-pw
FAMILIE_DOKUMENT_S3_ACCESSKEY: not-a-real-key
FAMILIE_DOKUMENT_S3_SECRETKEY: not-a-real-key

spring.main.allow-bean-definition-overriding": true