cors:
  allowed_origins:
    - "https://www-q0.nav.no"
    - "https://familie-ba-sak.dev.adeo.no"
    - "https://familie-ba-soknad-api.dev.nav.no"
    - "https://familie-ba-soknad.dev.nav.no"
    - "https://familie-ba-mottak.dev.adeo.no"
    - "https://familie-brev.dev.intern.nav.no"
    - "http://familie-brev.dev.intern.nav.no"
    - "https://familie-ef-blankett.dev.intern.nav.no"
    - "https://ensligmorellerfar.dev.nav.no"
    - "https://familie.dev.nav.no"

no.nav.security.jwt:
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookie_name: selvbetjening-idtoken
  issuer.tokenx:
    discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
    accepted_audience: ${TOKEN_X_CLIENT_ID}
