cors:
  allowed_origins:
    - "https://familie-ef-soknad.nais.oera-q.local"
    - "https://www-q0.nav.no/familie/alene-med-barn/soknad"
    - "https://familie-ef-soknad-api.nais.oera-q.local"

no.nav.security.jwt:
  issuers: selvbetjening
  issuer.selvbetjening:
    discoveryurl: ${LOGINSERVICE_IDPORTEN_DISCOVERY_URL}
    accepted_audience: ${LOGINSERVICE_IDPORTEN_AUDIENCE}
    cookie_name: selvbetjening-idtoken
