logging:
  config: "classpath:logback-e2e.xml"
no.nav.security.jwt:
  issuer:
    tokenx:
      discovery-url: http://localhost:${mock-oauth2-server.port}/tokenx/.well-known/openid-configuration
      accepted-audience: familie-app