cors:
  allowed_origins:
    - "https://www-q0.nav.no"
    - "https://familie-ba-sak.dev.adeo.no"
    - "https://familie-ba-soknad-api.dev.nav.no"
    - "https://familie-ba-soknad.dev.nav.no"
    - "https://familie-brev.intern.dev.nav.no"
    - "http://familie-brev.intern.dev.nav.no"
    - "https://familie-ef-blankett.intern.dev.nav.no"
    - "https://familie-ks-soknad.dev.nav.no"
    - "https://ensligmorellerfar.dev.nav.no"
    - "https://familie.dev.nav.no"

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: ${TOKEN_X_WELL_KNOWN_URL}
      accepted_audience: ${TOKEN_X_CLIENT_ID}
