apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-dokument
  namespace: teamfamilie
  labels:
    team: teamfamilie

spec:
  image: {{ image }}
  team: teamfamilie
  port: 8082
  liveness:
    path: /familie/alene-med-barn/mellomlagring/internal/status/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 27 # when a Pod starts and the probe fails,
  readiness:
    path: /familie/alene-med-barn/mellomlagring/internal/status/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: /familie/alene-med-barn/mellomlagring/internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: "1024Mi"
      cpu: "1000m"
    requests:
      memory: "512Mi"
      cpu: "500m"
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
    - https://familie-dokument.dev-gcp.nais.io
  accessPolicy:
    outbound:
      external:
        - host: familie-ba-sak.nais.preprod.local
        - host: login.microsoftonline.com
  azure:
    application:
      enabled: true
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: preprod
    - name: APP_TEAM
      value: teamfamilie
  #
  # the following spec is only available when running in GCP.
  #
  gcp:
    buckets:
      - name: familie-dokument-familievedlegg-dev
        cascadingDelete: false