apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-dokument
  namespace: teamfamilie
  labels:
    team: teamfamilie
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "25M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"

spec:
  image: {{ image }}
  team: teamfamilie
  port: 8082
  envFrom:
    - secret: {{ secret }}
    - configmap: loginservice-idporten
  liveness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10     # How often (in seconds) to perform the probe. Default to 10 seconds
    failureThreshold: 10 # when a Pod starts and the probe fails,
  readiness:
    path: /internal/status/isAlive
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 10
  prometheus:
    enabled: true
    path: /internal/prometheus
  vault:
    enabled: true
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 80
  resources:
    limits:
      memory: 4Gi
      cpu: "1"
    requests:
      memory: 2Gi
      cpu: 500m
  ingresses: # Optional. List of ingress URLs that will route HTTP traffic to the application.
{{#each ingresses as |url|}}
    - {{url}}
{{/each}}
  accessPolicy:
    inbound:
      rules:
        - application: familie-brev
        - application: familie-ef-blankett
        - application: soknad-kontantstotte-api
        - application: familie-ba-mottak
          cluster: {{ba-mottak-cluster}}
          namespace: teamfamilie
    outbound:
      rules:
        - application: clamav
          namespace: clamav
      external:
        - host: login.microsoftonline.com
  azure:
    application:
      enabled: true
  webproxy: false # Optional. Expose web proxy configuration to the application using the HTTP_PROXY, HTTPS_PROXY and NO_PROXY environment variables.
  secureLogs:
    enabled: true
  tokenx:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{spring_profile}}
    - name: APP_TEAM
      value: teamfamilie
    - name: GCP_STORAGE_BUCKETNAME
      value: {{bucket_name}}
  #
  # the following spec is only available when running in GCP.
  #
  gcp:
    buckets:
      - name: {{bucket_name}}
        cascadingDelete: false
        retentionPeriodDays: 2