name: Build og Deploy (dev)
on:
  workflow_dispatch:

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/familie-dokument:${{ github.sha }}

jobs:
  deploy-to-dev:
    name: Deploy til GCP (dev)
    runs-on: ubuntu-latest
    steps:
      - name: Deploy til GCP (dev)
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .deploy/naiserator.yaml
          VARS: .deploy/dev-gcp.json